# Type intermédiaire pour pouvoir récupérer précisément les utilisateurs
# depuis les données du parent qui est la table d'associations
# Le parent est la table d'associations, je précise bien car c'est important
type BookHasUser {

  user: User

}