type Book {

  # Le '!' ne signifi pas qu'il est obligatoire de récupérer l'id
  #  ça signifi que l'id récupéré doit forcément être du bon type et non pas null
  id: ID!
  isbn: String
  title: String
  author: String
  resume: String
  genre: [String]
  cover: String
  year: Int
  number_of_pages: Int

  # QUESTION ? Est-il possible de juste mettre User à la place de UserHasBook
  # Impossible, car users va récupérer seulement les accosiations
  # Il faut donc un type intermédiaire pour récupérer les utilisateurs en fonction des données de ces associations
  users: [BookHasUser]

}

type BookSubList {

  items: [Book!]!
  totalCount: Int!

}