type Query {
  
  user(id: Int!): User

  # UserSubLit est un tableau de User avec le totalCount
  users(limit: Int, offset: Int): UserSubList

  book(id: Int!): Book

  books(limit: Int, offset: Int): BookSubList

}