# Type intermédiaire pour pouvoir récupérer précisément les livres
# depuis les données du parent qui est la table d'associations
# Le parent est la table d'associations, je précise bien car c'est important
type UserHasBook {

  book: Book

}

# Attention, un enregistrement dans la table d'association se supprime tout seul
# A partir du moment ou l'une des deux clés de référence est supprimée (ON DELETE CASCADE)
input UserHasBookInputCreate {

  book_id: Int!
  user_id: Int!
  is_active: Boolean
  is_favorite: Boolean

}