@endpoint=http://localhost:{{$dotenv PORT}}

### Création d'un utilisateur O'Book Groove
POST {{endpoint}}/auth/signup
Content-Type: application/json

{
  
  "email":"toto@gmail.com",
  "pseudo":"Toto29",
  "password":"testMDP",
  "confirm_password":"testMDP"

}