@endpoint=http://localhost:{{$dotenv PORT}}

### Création d'un utilisateur O'Book Groove

POST {{endpoint}}/auth/signup
Content-Type: application/json

{
  "pseudo": "Mix",
  "email": "mix@oclock.io",
  "password": "Antestdefou3*",
  "confirmPassword": "Antestdefou3*"
}

### Connexion d'un utilisateur O'Book Groove
POST {{endpoint}}/auth/signin
Content-Type: application/json

{
  "email": "max@oclock.io",
  "password": "superpass"
}